* What happens when characters in Series?
* Loc and colon
* iLoc and colon
* Describe in string elements
* inplace error

# PANDAS

**INTRODUCTION  
Pandas is an open-source, Python library which provides easy-to-use data structures for the data analysis.**
**Pandas is great for data manipulation, data analysis, and data visualization.**

#### WHY PANDAS?

1. We can easily read and write from and to CSV files, or even databases
+ Easy handling of missing data (represented as NaN) in floating point as well as non-floating point data
+ We can manipulate the data by columns,.Columns can be inserted and deleted from DataFrame and higher dimensional objects
+ Intuitive merging and joining data sets
    5. Intelligent label-based slicing, fancy indexing, and subsetting of large data sets
    6. Robust IO tools for loading data from flat files (CSV and delimited), Excel files, databases, and saving/loading data.



In [3]:
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'pandas'

# Series
A series is a 1-D data structure. It is basically a labelled array that can hold different data types:
* int
* float
* String
* Python object
* many more

The data is aligned in a row fashon.

## Creating the series from the random dataset_for_series

In [5]:
a = np.random.randint(10) 

NameError: name 'np' is not defined

In [3]:
np.random.seed(10)
data_for_series = np.random.randint(0, 100, 10)
print(data_for_series)

[ 9 15 64 28 89 93 29  8 73  0]


In [97]:
s = pd.Series(data_for_series)

In [98]:
print(s)

0     9
1    15
2    64
3    28
4    89
5    93
6    29
7     8
8    73
9     0
dtype: int64


We can get the information

## Using Label (String Index)

In [105]:
index_for_series = 'A B C D E F G H I J'.split(' ')


In [106]:
print(index_for_series)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']


In [107]:
char_series = pd.Series(data_for_series, index=index_for_series)

In [149]:
print(char_series)


A     9
B    15
C    64
D    28
E    89
F    93
G    29
H     8
I    73
J     0
dtype: int64


In [155]:
char_series[2]

64

In [1]:
#get the datas 9,15,64
char_series[0:4]


NameError: name 'char_series' is not defined

In [166]:
#get the datas 9,64,89
char_series[0:6:2]


## DATAFRAME

A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns. A pandas DataFrame can be created using the following constructor −

```python
pandas.DataFrame(data, index, columns)
```

## Creating random data

In [12]:
np.random.seed(3)
data = np.random.randint(0, 10, (5, 4)) # Ranging from 0-10 with 5*4 matrix

In [61]:
print(data)

[[8 9 3 8]
 [8 0 5 3]
 [9 9 5 7]
 [6 0 4 7]
 [8 1 6 2]]


In [13]:
pd.DataFrame(data)

0  1  2  3
0  8  9  3  8
1  8  0  5  3
2  9  9  5  7
3  6  0  4  7
4  8  1  6  2

In [14]:
my_index = 'P Q R S T'.split()
my_columns = 'A B C D'.split()
df = pd.DataFrame(data, index=my_index, columns=my_columns)
df

A  B  C  D
P  8  9  3  8
Q  8  0  5  3
R  9  9  5  7
S  6  0  4  7
T  8  1  6  2

In [117]:
df["A"]

P    8
Q    8
R    9
S    6
T    8
Name: A, dtype: int64

## Checking the information

In [64]:
df.describe()

A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   7.800000  3.800000  4.600000  5.400000
std    1.095445  4.764452  1.140175  2.701851
min    6.000000  0.000000  3.000000  2.000000
25%    8.000000  0.000000  4.000000  3.000000
50%    8.000000  1.000000  5.000000  7.000000
75%    8.000000  9.000000  5.000000  7.000000
max    9.000000  9.000000  6.000000  8.000000

## Selecting elements using Label
Selecting a single row or column returns a Series while selecting multilple gives a DataFrame.  
First parameter is the row and select parameter is the column and is optional.

In [110]:
df

A  B  C  D
P  8  9  3  8
Q  8  0  5  3
R  9  9  5  7
S  6  0  4  7
T  8  1  6  2

The column names become the labels for the output.

In [124]:
df.loc[['Q', 'S']]

A  B  C  D
Q  8  0  5  3
S  6  0  4  7

In [125]:
df.iloc[[0,3]]

A  B  C  D
P  8  9  3  8
S  6  0  4  7

In [140]:
df

A  B  C  D
P  8  9  3  8
Q  8  0  5  3
R  9  9  5  7
S  6  0  4  7
T  8  1  6  2

We can take column using the second parameter. 
*The colon **:** implies all of the elements for that dimension.*

In [129]:
df.iloc[:,2:]

C  D
P  3  8
Q  5  3
R  5  7
S  4  7
T  6  2

In [69]:
df.iloc[0:2,0:5 ]

A  B  C  D
P  8  9  3  8
Q  8  0  5  3

In [168]:
df.loc[["P", "T"], ["A", "C", "D"]]

A  C  D
P  8  3  8
T  8  6  2

In [174]:
df

A  B  C  D
P  8  9  3  8
Q  8  0  5  3
R  9  9  5  7
S  6  0  4  7
T  8  1  6  2

In [178]:
#get the columns A and D
df.iloc[:,0::3]


# Titanic

## Load CSV File

In [1]:
train_df = pd.read_csv("Titanic_train.csv")

NameError: name 'pd' is not defined

In [180]:
train_df.head(4)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [181]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


## Drop 

* Cabin data is sparse so remove it.
* Name is complex to use, so remove that column.
* Ticket is complex to use, so remove that column.

In [182]:
train_df.drop("Cabin", axis=1)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

In [183]:
train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

<br>
<br>
To drop in the Original dataframe, use **inplace**.

In [22]:
train_df.drop("Name", axis=1, inplace=True)

In [23]:
train_df.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

<br>
<br>
To remove multiple columns, use **list** parameter.

In [21]:
train_df.drop(["Ticket", "Cabin"], axis=1, inplace=True)

In [79]:
train_df.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [80]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(2)
memory usage: 62.7+ KB


* Age has null data
* Embarked has null data

## Empty data

In [34]:
train_df["Embarked"]

0      S
1      C
2      S
3      S
4      S
5      Q
6      S
7      S
8      S
9      C
10     S
11     S
12     S
13     S
14     S
15     S
16     Q
17     S
18     S
19     C
20     S
21     S
22     Q
23     S
24     S
25     S
26     C
27     S
28     Q
29     S
      ..
861    S
862    S
863    S
864    S
865    S
866    C
867    S
868    S
869    S
870    S
871    S
872    S
873    S
874    C
875    C
876    S
877    S
878    S
879    C
880    S
881    S
882    S
883    S
884    S
885    Q
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [28]:
null_embarked = train_df["Embarked"].isnull()

In [29]:
null_embarked.head()

0    False
1    False
2    False
3    False
4    False
Name: Embarked, dtype: bool

In [30]:
train_df[null_embarked]

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  Fare Embarked
61            62         1       1  female  38.0      0      0  80.0      NaN
829          830         1       1  female  62.0      0      0  80.0      NaN

In [35]:
train_df["Embarked"].describe()

count     889
unique      3
top         S
freq      644
Name: Embarked, dtype: object

### Filling empty Embarked with Mode

In [72]:
train_df["Embarked"].fillna("S", inplace=True)

In [73]:
null_embarked = train_df["Embarked"].isnull()
train_df[null_embarked]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
Index: []

No Empty Embarked column

In [74]:
train_df['Age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
5      29.699118
6      54.000000
7       2.000000
8      27.000000
9      14.000000
10      4.000000
11     58.000000
12     20.000000
13     39.000000
14     14.000000
15     55.000000
16      2.000000
17     29.699118
18     31.000000
19     29.699118
20     35.000000
21     34.000000
22     15.000000
23     28.000000
24      8.000000
25     38.000000
26     29.699118
27     19.000000
28     29.699118
29     29.699118
         ...    
861    21.000000
862    48.000000
863    29.699118
864    24.000000
865    42.000000
866    27.000000
867    31.000000
868    29.699118
869     4.000000
870    26.000000
871    47.000000
872    33.000000
873    47.000000
874    28.000000
875    15.000000
876    20.000000
877    19.000000
878    29.699118
879    56.000000
880    25.000000
881    33.000000
882    22.000000
883    28.000000
884    25.000000
885    39.000000
886    27.000000
887    19.000000
888    29.6991

### Filling empty Age with mean of that column

In [75]:
age_null = train_df["Age"].isnull()
train_df[age_null]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
Index: []

In [76]:
age_mean = train_df["Age"].mean()

In [77]:
age_mean

29.699117647058763

In [78]:
train_df["Age"].fillna(age_mean, inplace=True)

No empty Age value afterwards

In [79]:
new_age_null = train_df["Age"].isnull()
train_df[new_age_null]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
Index: []

## Data Mapping
Mapping Characters to numeric values because Machine learning models only understand numbers.

In [80]:
embark_maps = {
    "C" : 1,
    "S" : 2,
    "Q" : 3
}

In [81]:
train_df["Embarked"] = train_df["Embarked"].map(embark_maps)

In [82]:
train_df.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0            1         0       3    male  22.0      1      0   7.2500   
1            2         1       1  female  38.0      1      0  71.2833   
2            3         1       3  female  26.0      0      0   7.9250   
3            4         1       1  female  35.0      1      0  53.1000   
4            5         0       3    male  35.0      0      0   8.0500   

   Embarked  
0         2  
1         2  
2         2  
3         2  
4         2

In [83]:
gender_maps = {
    "male" : 1,
    "female" : 2
}

In [84]:
train_df["Sex"] = train_df["Sex"].map(gender_maps)

In [85]:
train_df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500         2
1            2         1       1    2  38.0      1      0  71.2833         2
2            3         1       3    2  26.0      0      0   7.9250         2
3            4         1       1    2  35.0      1      0  53.1000         2
4            5         0       3    1  35.0      0      0   8.0500         2

In [86]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null int64
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       891 non-null int64
dtypes: float64(2), int64(7)
memory usage: 62.7 KB


# Save to CSV File

In [87]:
train_df.to_csv("Titanic_train_numeric.csv", index=False)

train_df

In [96]:

train_df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500         2
1            2         1       1    2  38.0      1      0  71.2833         2
2            3         1       3    2  26.0      0      0   7.9250         2
3            4         1       1    2  35.0      1      0  53.1000         2
4            5         0       3    1  35.0      0      0   8.0500         2